### ISSUE TITLE
opencart 2.2.0.0

### ISSUE THREAD

**Issue by pbulany** [opencart-ukraine/translate#16]
Помилка при українізації сайту нової версії opencart 2.2.0.0. На минулих версіях все працювало.
Хто як поборов?

**Comment by pbulany** [comment]
Допомагає перейменування каталогу з "Ukrainian" на коротшу назву, наприклад, "ua".

**Comment by dinox-pro** [comment]
Зараз йдуть роботи над адаптацією перекладу під 2.3.0.2 в ній ця проблема буде виплавлена
