### ISSUE TITLE
некоректне відображення шрифту на OCstore 1.5.5....

### ISSUE THREAD

**Issue by seotop** [opencart-ukraine/translate#5]
Доброго дня.
При встановленні цього пакету на OCstore 1.5.5.... постійно вилітає помилка в стрічці 39 і всі меню некорректно відображаються.
пакет локалізаціі скачаний з опенкарт.вс стає нормально.

**Comment by dinox-pro** [comment]
В подальшому ми будемо перевіряти переклад на популярних сбірках OpenCart
